
name: Create DOZ Keystore

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  create-keystore:
    runs-on: ubuntu-latest

    env:
      KEYSTORE_PASSWORD: "Mani_3840494915_Mani"

    steps:

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'

      - name: Create Keystore
        run: |
          keytool -genkeypair \
            -v \
            -keystore doz-release.keystore \
            -alias doz \
            -keyalg RSA \
            -keysize 4096 \
            -validity 10000 \
            -storepass "$KEYSTORE_PASSWORD" \
            -keypass "$KEYSTORE_PASSWORD" \
            -dname "CN=DOZ, OU=Game, O=DOZ, L=Game, ST=Game, C=XX"

      - name: Create Base64 File
        run: |
          base64 -w 0 doz-release.keystore > keystore-base64.txt

      - name: Create Info File
        run: |
          cat > keystore-info.txt <<EOF
          ANDROID_KEY_ALIAS=doz
          ANDROID_KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD
          ANDROID_KEY_PASSWORD=$KEYSTORE_PASSWORD
          EOF

      - name: Upload Keystore Information
        uses: actions/upload-artifact@v4
        with:
          name: DOZ-Keystore-Info
          path: |
            keystore-base64.txt
            keystore-info.txt
